import { SchoolTheme, LostItem, Category } from './types';

export const CATEGORIES: Category[] = ['Clothing', 'Electronics', 'Books', 'Musical', 'Personal', 'Other'];
export const ADMIN_PASSWORD = "8290";

export const SCHOOL_THEMES: Record<string, SchoolTheme> = {
  will_east: { id: 'will_east', name: 'Williamsville East High School', logo: '/images/east.png', palette: { primary: '#ed1e25', secondary: '#f8ec24', tertiary: '#000000' }, contactInfo: { address: '151 Paradise Rd, East Amherst, NY 14051', phone: '(716) 626-8400', email: 'eastoffice@williamsvillek12.org', principal: 'Mr. Brian Swatland' } },
  will_north: { id: 'will_north', name: 'Williamsville North High School', logo: '/images/north.png', palette: { primary: '#295236', secondary: '#ebe537', tertiary: '#b3a168' }, contactInfo: { address: '1595 Hopkins Rd, Williamsville, NY 14221', phone: '(716) 626-8500', email: 'northoffice@williamsvillek12.org', principal: 'Mrs. Julie Barber' } },
  will_south: { id: 'will_south', name: 'Williamsville South High School', logo: '/images/south.png', palette: { primary: '#20366c', secondary: '#fbf9d2', tertiary: '#eaa55e' }, contactInfo: { address: '5950 Main St, Williamsville, NY 14221', phone: '(716) 626-8200', email: 'southoffice@williamsvillek12.org', principal: 'Dr. Ryan M. Bialas' } },
  transit_middle: { id: 'transit_middle', name: 'Transit Middle School', logo: '/images/transit.png', palette: { primary: '#79242f', secondary: '#aca9b7', tertiary: '#000000' }, contactInfo: { address: '8730 Transit Rd, East Amherst, NY 14051', phone: '(716) 626-8700', email: 'transitoffice@williamsvillek12.org', principal: 'Mr. Daniel Walh' } },
  mill_middle: { id: 'mill_middle', name: 'Mill Middle School', logo: '/images/mill.png', palette: { primary: '#264e99', secondary: '#b5badb', tertiary: '#000000' }, contactInfo: { address: '8524 Mill St, Williamsville, NY 14221', phone: '(716) 626-8300', email: 'milloffice@williamsvillek12.org', principal: 'Mrs. Lasky' } },
  heim_middle: { id: 'heim_middle', name: 'Heim Middle School', logo: '/images/heim-middle.png', palette: { primary: '#bf202f', secondary: '#fdb719', tertiary: '#77787a' }, contactInfo: { address: '175 Heim Rd, Williamsville, NY 14221', phone: '(716) 626-8600', email: 'heimmiddle@williamsvillek12.org', principal: 'Mr. Jeffrey Jachlewski' } },
  casey_middle: { id: 'casey_middle', name: 'Casey Middle School', logo: '/images/casey.png', palette: { primary: '#00463c', secondary: '#ffcb2c', tertiary: '#b27a3c' }, contactInfo: { address: '105 Casey Rd, East Amherst, NY 14051', phone: '(716) 626-8600', email: 'caseyoffice@williamsvillek12.org', principal: 'Mr. Peter Dobmeier' } },
  country_parkway: { id: 'country_parkway', name: 'Country Parkway Elementary School', logo: '/images/country-parkway.png', palette: { primary: '#4d286a', secondary: '#f4eb2e', tertiary: '#231f20' }, contactInfo: { address: '35 Hollybrook Dr, Williamsville, NY 14221', phone: '(716) 626-9860', email: 'cpoffice@williamsvillek12.org', principal: 'Mr. Andrew Bowen' } },
  dodge_elementary: { id: 'dodge_elementary', name: 'Dodge Elementary School', logo: '/images/dodge.png', palette: { primary: '#1e5732', secondary: '#fbd702', tertiary: '#000000' }, contactInfo: { address: '1900 Dodge Rd, East Amherst, NY 14051', phone: '(716) 626-9820', email: 'dodgeoffice@williamsvillek12.org', principal: 'Mr. Charles Smilinich' } },
  forest_elementary: { id: 'forest_elementary', name: 'Forest Elementary School', logo: '/images/forest.png', palette: { primary: '#aa6e29', secondary: '#231f20', tertiary: '#ffffff' }, contactInfo: { address: '250 N Forest Rd, Williamsville, NY 14221', phone: '(716) 626-9800', email: 'forestoffice@williamsvillek12.org', principal: 'Mrs. Keith' } },
  maple_east: { id: 'maple_east', name: 'Maple East Elementary School', logo: '/images/maple-east.png', palette: { primary: '#27398b', secondary: '#d6b683', tertiary: '#9ca1a3' }, contactInfo: { address: '1500 Maple Rd, Williamsville, NY 14221', phone: '(716) 626-8800', email: 'mapleeast@williamsvillek12.org', principal: 'Mrs. Cathy Mihalic' } },
  maple_west: { id: 'maple_west', name: 'Maple West Elementary School', logo: '/images/maple-west.png', palette: { primary: '#00984c', secondary: '#f68620', tertiary: '#d26428' }, contactInfo: { address: '851 Maple Rd, Williamsville, NY 14221', phone: '(716) 626-8840', email: 'maplewest@williamsvillek12.org', principal: 'Mr. Charles Galluzzo' } },
  heim_elementary: { id: 'heim_elementary', name: 'Heim Elementary School', logo: '/images/heim-elementary.png', palette: { primary: '#ac1f24', secondary: '#1e4480', tertiary: '#c4c6d8' }, contactInfo: { address: '155 Heim Rd, Williamsville, NY 14221', phone: '(716) 626-8680', email: 'heimelem@williamsvillek12.org', principal: 'Ms. Bonnie Stafford' } },
};

//This section is merely for presentation purposes. Can be removed.
export const INITIAL_ITEMS: LostItem[] = [
  { id: '1', name: 'Red Gym Bag', description: 'Left in the locker room near the showers.', category: 'Personal', schoolId: 'will_east', date: '2023-10-24', status: 'lost', imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=300&h=300' },
  { id: '2', name: 'Physics Textbook', description: 'Found in the science wing hallway.', category: 'Books', schoolId: 'will_north', date: '2023-10-25', status: 'found', imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=300&h=300' },
  { id: '3', name: 'Blue Hoodie', description: 'Size M. Left in Cafeteria.', category: 'Clothing', schoolId: 'will_south', date: '2023-10-26', status: 'lost', imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&q=80&w=300&h=300' },
  { id: '4', name: 'Violin Case', description: 'Black hard case found in the music room.', category: 'Musical', schoolId: 'transit_middle', date: '2023-10-27', status: 'found', imageUrl: 'https://images.unsplash.com/photo-1612225330812-01a9c6b355ec?auto=format&fit=crop&q=80&w=300&h=300' }
];
